import { Button, Card, CardActions, CardContent, Grid, Typography } from '@mui/material'
import type { InferGetServerSidePropsType } from 'next'
import Head from 'next/head'

import Layout from '@/components/Layout'
import campaignFactory from '@/interfaces/campaignFactory'

export const getServerSideProps = async () => {
  const activeCampaigns: string[] = await campaignFactory.methods.getDeployedCampaigns().call()
  return {
    props: {
      activeCampaigns
    }
  }
}

const Home = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <Layout>
      <Head>
        <title>Franco&apos;s Kickstarter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={3} padding={3}>
        <Grid item xs={8}>
          <Typography gutterBottom variant="h6">Open campaigns</Typography>
          {props.activeCampaigns.map((campaignAddress, index) => (
            <Card key={campaignAddress}>
              <CardContent>
                <Typography variant="h5" component="h2">
                  Campaign {index + 1}
                </Typography>
                <Typography variant="body1">At address {campaignAddress}</Typography>
              </CardContent>
              <CardActions>
                <Button size="small">View Campaign</Button>
              </CardActions>
            </Card>
          ))}
        </Grid>
        <Grid
          item
          xs={4}
          mt={5}
        >
          <Button variant="contained" color="secondary" fullWidth>
            Create new campaign
          </Button>
        </Grid>
      </Grid>
    </Layout>
  )
}

export default Home
